services:
  db:
    image: pgvector/pgvector:pg18-trixie
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag-bot
      TZ: Asia/Tokyo
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - "55432:5432"
    restart: always
